security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto
            cost: 15

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/(app|login|logout)
            form_login:
                login_path: app_login
                check_path: app_login
                provider: all_users
                use_referer: true
            logout:
                path: app_logout
                target: /
        api:
            pattern: ^/api
            security: true
            provider: base_user_provider
            access_token:
                token_handler: App\Security\AccessTokenHandler
                token_extractors:
                    - 'header'

    access_control:
        - { path: ^/app, roles: ROLE_APP }
        - { path: ^/api, roles: ROLE_API }

    providers:
        base_user_provider:
            id: App\Security\UserProvider
        backend_users:
            memory:
                users:
                    test: { password: '$2y$15$wV8OMmsJRGBVLEAauSiwteAB1pgpctjtQEaHNYgpIZLdJrWAv5rAK', roles: ['ROLE_APP', 'ROLE_API'] }
        all_users:
            chain:
                providers: ['base_user_provider', 'backend_users']

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 15
                time_cost: 3
                memory_cost: 10
