twig:
    default_path: '%kernel.project_dir%/templates'
    auto_reload: '%kernel.debug%'
    cache: false

    globals:
        app_name: '%env(APP_NAME)%'
        app_description: '%env(APP_DESCRIPTION)%'
        app_author: '%env(APP_AUTHOR)%'

    form_themes:
        - 'resources/form/fields.html.twig'

when@test:
    twig:
        strict_variables: true
